language: en
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: "FallbackPolicy"
  nlu_threshold: 0.3
  ambiguity_threshold: 0.1
  core_threshold: 0.3
  fallback_action_name: 'utter_default'
- name: MappingPolicy